# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f5efb345-089d-4dbb-bfa7-e1960a4b4bac";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-f5efb345-089d-4dbb-bfa7-e1960a4b4bac".device = "/dev/disk/by-uuid/f5efb345-089d-4dbb-bfa7-e1960a4b4bac";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-f5efb345-089d-4dbb-bfa7-e1960a4b4bac";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-f5efb345-089d-4dbb-bfa7-e1960a4b4bac";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AE68-696B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b09d7810-0130-4418-b06b-320d01684396"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
